### ISSUE TITLE
Custom telemetry service

### ISSUE THREAD

**Issue by madhu-aithal** [project-sunbird/sunbird-telemetry-sdk#2]
I am trying to use sunbird-telemetry-sdk in my angular web app. I have set up a custom telemetry service in a VM. I want this SDK to push the data to my custom telemetry service, instead of ekstep telemetry service. For this, I am specifying the VM IP in the host field of config parameter of sdk's 'start' API. However, it is not pushing the data to backend service or showing any error in the console. Am I configuring it properly or am I missing something? Also, is it actually possible to use our backend telemetry service with this sdk instead of ekstep telemetry service?

**Comment by manjudr** [comment]
@madhu-aithal 
Yes, It should work.

I hope you are passing `host` and `endpoint `.
May i know what request url is going ? and what response you are getting in the network? can you share more details.

By default `endpoint` is `/v3/telemetry` and you can override this endpoint by passing as configuration.

**Comment by madhu-aithal** [comment]
@manjudr 
Now I am able to use SDK with our own telemetry service by passing the `host` and `endpoint` in the configuration.

Thank you.
